# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: 'Learn / Software Development'
nav:
- Home: index.md
- What Job will the Software Do?:  software-job.md
- Overview of Software Development:  overview.md
- Development Environment Tools:
  - Overview:  dev-env-tools/overview.md
  - Operating System:  dev-env-tools/os.md
  - Compiler:  dev-env-tools/compiler.md
  - Text Editor:  dev-env-tools/editor.md
  - Difference tool:  dev-env-tools/diff.md
  - IDE: dev-env-tools/ide.md
  - Runtime Environment:  dev-env-tools/runtime.md
  - Version Control:  dev-env-tools/version-control.md
  - Documentation:  dev-env-tools/doc.md
  - Logging:  dev-env-tools/logging.md
  - Debugger:  dev-env-tools/debugger.md
  - Test Framework:  dev-env-tools/test.md
  - Installer:  dev-env-tools/installer.md
- Development Environment by Language:
  - Overview: dev-env-by-lang/overview.md
  - Script (Linux/Bash):  dev-env-by-lang/bash.md
  - Script (Windows/Batch File):  dev-env-by-lang/bat.md
  - Script (Windows/PowerShell):  dev-env-by-lang/powershell.md
  - C:  dev-env-by-lang/c.md
  - 'C#':  dev-env-by-lang/csharp.md
  - Fortran:  dev-env-by-lang/fortran.md
  - Java:  dev-env-by-lang/java.md
  - Python:  dev-env-by-lang/python.md
  - Web (JavaScript):  dev-env-by-lang/web-javascript.md
#- Resources: resources.md
# ------- configuration properties ---------------
# Alphabetize
# ------------------------------------------------
copyright:  'Copyright Open Water Foundation'
# Use extra CSS to customize styles, based on theme.
extra_css:
  - 'css/extra-material-theme.css'
# ------------------------------------------------
# Google Analytics:
# - see:  https://squidfunk.github.io/mkdocs-material/getting-started/#google-analytics
extra:
  analytics:
    provider: google
    property: 'G-KJFMBY739T'
# ------------------------------------------------
# Don't indicate the repo because Edit will be shown on every page (don't want that in deployed mode)
# - Also see edit_uri if repo_url is specified
#repo_url:  https://github.com/OpenWaterFoundation/owf-learn-software-dev
site_author:  'Open Water Foundation'
site_description:  'Open Water Foundation Learn Software Development'
# ------------------------------------------------
# Use Material theme:
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme:
  name: 'material'
  favicon: 'images/OWF-Logo-Favicon-32x32.png'
